version: '3.7'
services: 

  # Caddy Server
  caddy:
    image: caddy/caddy:2.6.4-alpine
    container_name: caddy-service
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
    - $PWD/Caddyfile:/etc/caddy/Caddyfile
    - $PWD/site:/srv
    - caddy_data:/data
    - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:

# networks:
#   backend:
#   frontend: